version: '3'

services:
  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - deploy/env/.env.local
    command: --port ${REDIS_PORT}