version: '3'

volumes:
  postgres_volume:

services:
  storage:
    image: postgres:16.1
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - deploy/env/.env.test
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p ${PG_PORT}

  redis:
    image: redis:7.2.4
    restart: always
    expose:
      - "${REDIS_PORT}"
    env_file:
      - deploy/env/.env.test
    command: --port ${REDIS_PORT}

  migrator:
    build:
      dockerfile: deploy/dockerfiles/migrator.Dockerfile
    env_file:
      - deploy/env/.env.test
    depends_on:
      - storage
    environment:
      PG_HOST: storage

  app:
    build:
      context: .
      dockerfile: deploy/dockerfiles/exchange_test.Dockerfile
    env_file:
      - deploy/env/.env.test
    depends_on:
      - redis
      - storage
    environment:
      PG_HOST: storage
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    restart: on-failure

  e2e:
    build:
      context: .
      dockerfile: deploy/dockerfiles/test.Dockerfile
    depends_on:
      - app
    environment:
      HTTP_HOST: app
      HTTP_PORT: "${HTTP_PORT}"
    command: ["go", "test", "-tags", "e2e", "./...", "-count=1"]

